### ISSUE TITLE
it creates the output directory but not the files

### ISSUE THREAD

**Issue by blackgis** [sharedstreets/sharedstreets-builder#17]
I cd to my current location where the files are and when i execute

**Comment by blackgis** [comment]
java -jar ./sharedstreets-builder-0.3.1.jar --input data/nyc_test.pbf --output ./outcome
it starts heavely but when it is finished there are no files in the outcome folder

**Comment by hbruch** [comment]
What do you mean by 'it starts heavily'? Could you append (some) log output? Perhaps you are executing in the wrong directory?

The following steps for me were successful:

```
> gradle allJars
...
> java -jar build/libs/sharedstreets-builder-0.3.1.jar --input data/nyc_test.pbf --output ./outcome
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Connected to JobManager at Actor[akka://flink/user/jobmanager_1#1180750838] with leader session id 66d9aa3e-bc0d-4d20-9f4f-00f6ab58cef9.
06/08/2019 13:46:02	Job execution switched to status RUNNING.
06/08/2019 13:46:02	CHAIN DataSource (at <init>(OSMDataStream.java:74) (io.sharedstreets.tools.builder.osm.inputs.OSMPBFWayInputFormat)) -> Map (Key Extractor)(1/12) switched to SCHEDULED
06/08/2019 13:46:02	CHAIN DataSource (at <init>(OSMDataStream.java:74) (io.sharedstreets.tools.builder.osm.inputs.OSMPBFWayInputFormat)) -> Map (Key Extractor)(1/12) switched to DEPLOYING
...
06/08/2019 13:39:44	DataSink (io.sharedstreets.tools.builder.tiles.ProtoTileOutputFormat@2b4a2ec7)(5/12) switched to FINISHED
06/08/2019 13:39:44	DataSink (io.sharedstreets.tools.builder.tiles.ProtoTileOutputFormat@2b4a2ec7)(10/12) switched to FINISHED
06/08/2019 13:39:44	Job execution switched to status FINISHED.
> ls outcome/
12-1205-1541.geometry.4.pbf	12-1205-1541.intersection.6.pbf	12-1205-1541.reference.4.pbf	12-1206-1541.geometry.6.pbf	12-1206-1541.metadata.4.pbf	12-1206-1541.reference.6.pbf
12-1205-1541.geometry.6.pbf	12-1205-1541.metadata.4.pbf	12-1205-1541.reference.6.pbf	12-1206-1541.intersection.4.pbf	12-1206-1541.metadata.6.pbf
12-1205-1541.intersection.4.pbf	12-1205-1541.metadata.6.pbf	12-1206-1541.geometry.4.pbf	12-1206-1541.intersection.6.pbf	12-1206-1541.reference.4.pbf
```
