### ISSUE TITLE
Failing SharedStreetsIdTest

### ISSUE THREAD

**Issue by hbruch** [sharedstreets/sharedstreets-builder#20]
When running grade build on the current master, the SharedStreetsIdTest fails:

org.junit.ComparisonFailure: expected:<2[f8927dd68e7ed8d1b7ff16e979b83ae]> but was:<2[456bffd0ffca31eaaeb81f627415e29]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.sharedstreets.tools.builder.util.SharedStreetsIdTest.evaluate(SharedStreetsIdTest.java:33)

**Comment by hbruch** [comment]
This issue is caused by #22, so closing here
